<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>MinesweeperUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinesweeperCore\MinesweeperCore.csproj" />
  </ItemGroup>

</Project>
